/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:2db34a5c-9558-4a55-8336-aeca1b06f897",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_P1bMum0Ka",
    "aws_user_pools_web_client_id": "5ls5vj29j45ogk6bt6hu2b63jm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://adxitqtfgvfyzevqtki7na36tq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5pvy2mdx3vh4reftfdvtgxpszm",
    "aws_user_files_s3_bucket": "your-unique-bucket-name163831-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
